# Generated by Django 5.1.2 on 2024-12-01 21:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('label', models.CharField(choices=[('Malware', 'Malware'), ('Goodware', 'Goodware')], max_length=20)),
                ('localizacao', models.BooleanField(default=False)),
                ('rede', models.BooleanField(default=False)),
                ('bluetooth', models.BooleanField(default=False)),
                ('armazenamento', models.BooleanField(default=False)),
                ('sistema', models.BooleanField(default=False)),
                ('message', models.BooleanField(default=False)),
                ('midia_audio', models.BooleanField(default=False)),
                ('biblioteca_classes', models.BooleanField(default=False)),
                ('pacotes', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='softwares', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
