# Generated by Django 5.1.2 on 2024-11-02 00:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safeclean', '0002_software_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='software',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterField(
            model_name='software',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='software',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='softwares', to=settings.AUTH_USER_MODEL),
        ),
    ]
