# Generated by Django 5.1.2 on 2024-11-02 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safeclean', '0003_alter_software_options_alter_software_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='software',
            options={},
        ),
    ]
