# Generated by Django 5.1.2 on 2024-11-02 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safeclean', '0004_alter_software_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software',
            name='name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
