# Generated by Django 5.1.2 on 2024-11-02 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safeclean', '0008_software_armazenamento_externo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='software',
            name='armazenamento_externo',
        ),
        migrations.RemoveField(
            model_name='software',
            name='audio_hardware',
        ),
        migrations.RemoveField(
            model_name='software',
            name='localizacao_rede',
        ),
        migrations.RemoveField(
            model_name='software',
            name='mensagens_chamada',
        ),
        migrations.RemoveField(
            model_name='software',
            name='sistema_processos',
        ),
    ]
